[tool.mypy]
# Ensure we know what we do
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true

# Imports management
ignore_missing_imports = true
follow_imports = "normal"

# Ensure full coverage
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true

# Restrict dynamic typing (a little)
# e.g. `x: List[Any]` or x: List`
disallow_any_generics = true

# From functions not declared to return Any
warn_return_any = true

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
fixable = ["ALL"]
extend-select = ["ALL"]
ignore = [
    "ANN401",   # Any
    "D",        # no really needed
    "DTZ007",   # naive datetime
    "COM812",   # conflict
    "E501",     # line too long
    "ISC001",   # conflict
    "T201",     # `print()`
]